import { LegalPageLayout } from "@/components/legal/legal-page-layout";

export default function DisclaimerPage() {
  return (
    <LegalPageLayout title="FINANCIAL DISCLAIMER" lastUpdated="MARCH 2026">
      {/* Warning Banner */}
      <div className="border border-bearish/30 bg-bearish/5 p-4 md:p-6">
        <div className="flex items-start gap-3">
          <span className="text-bearish text-lg font-bold shrink-0">!!</span>
          <div>
            <div className="text-sm font-bold tracking-widest text-bearish mb-2">
              IMPORTANT WARNING
            </div>
            <p className="text-xs text-foreground/80">
              ShadowBrokers is an informational tool only. Nothing on this platform constitutes financial advice, investment advice, trading advice, or any other form of professional advice. You should not make any financial decisions based solely on information provided by this Service. Always consult a qualified financial advisor before making investment decisions.
            </p>
          </div>
        </div>
      </div>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">1. NOT FINANCIAL ADVICE</h2>
        <p>
          The content provided by ShadowBrokers — including sentiment analysis, confidence scores, predicted directions, market briefings, and danger zone alerts — is generated by artificial intelligence for informational and educational purposes only. None of this content constitutes a recommendation to buy, sell, hold, or otherwise transact in any security, financial instrument, or cryptocurrency. We are not a registered investment advisor, broker-dealer, or financial planner.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">2. AI-GENERATED ANALYSIS</h2>
        <p>
          All analysis on this platform is generated by large language models (LLMs) processing publicly available news articles. AI-generated content may be inaccurate, incomplete, outdated, or biased. The models may misinterpret news articles, assign incorrect sentiment, or produce unreliable confidence scores. AI outputs should never be treated as factual statements or reliable predictions.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">3. NO GUARANTEES</h2>
        <p>
          We make no guarantees regarding the accuracy, reliability, completeness, or timeliness of any information provided through the Service. Market data may be delayed or inaccurate. Sentiment analysis may not reflect actual market conditions. Predicted directions and magnitudes are probabilistic estimates, not certainties. Past accuracy rates do not guarantee future performance.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">4. RISK DISCLOSURE</h2>
        <p>
          Trading and investing in financial markets involves substantial risk of loss. You may lose some or all of your invested capital. The value of investments can go down as well as up. Leveraged products carry additional risks. You should only trade with money you can afford to lose. Market volatility, liquidity conditions, and geopolitical events can cause rapid and unpredictable price movements.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">5. PAST PERFORMANCE</h2>
        <p>
          Any historical data, accuracy metrics, or backtested results shown on the platform are for informational purposes only. Past performance is not indicative of future results. Historical accuracy of AI predictions does not guarantee that future predictions will be accurate. Market conditions change constantly and models that performed well historically may not continue to do so.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">6. INDEPENDENT RESEARCH</h2>
        <p>
          You are solely responsible for evaluating the merits and risks of any investment decision. Before making any financial decision, you should: (a) conduct your own independent research and analysis; (b) consider your personal financial situation, goals, and risk tolerance; (c) consult with qualified financial, legal, and tax professionals; (d) review official filings, reports, and disclosures from relevant regulatory bodies (SEC, ESMA, etc.).
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">7. LIMITATION OF LIABILITY</h2>
        <p>
          UNDER NO CIRCUMSTANCES SHALL SHADOWBROKERS, ITS FOUNDERS, EMPLOYEES, AFFILIATES, OR AGENTS BE LIABLE FOR ANY LOSSES, DAMAGES, OR COSTS ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON ANY INFORMATION PROVIDED BY THE SERVICE. THIS INCLUDES, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR LOSS OF INVESTMENT CAPITAL, REGARDLESS OF WHETHER WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
      </section>

      <section>
        <h2 className="text-sm md:text-base font-bold tracking-widest text-foreground mb-3">8. ACKNOWLEDGMENT</h2>
        <p>
          By using ShadowBrokers, you acknowledge that you have read, understood, and agree to this Financial Disclaimer. You accept full responsibility for any investment decisions you make and agree that ShadowBrokers is not liable for any financial outcomes resulting from your use of the Service. If you do not agree with this disclaimer, you should not use the Service.
        </p>
      </section>
    </LegalPageLayout>
  );
}
